name = "Re-Console Lite"
author = "omo50"
version = "1.0.1+mc1.21.5+fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e10ffb4688f9d6a22b70b483ed3cdad819b228c16d0e80697bbd4a9cec521175"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
