name = "Re-Console Lite"
author = "omo50"
version = "1.0.0+mc1.21.5+fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef15e31bb876c5bfa2827f77d6a69d341fd7f9cbab06edfba27fba1d57a7ef02"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
