name: Feature request
description: Request a feature to be added.
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like added?
      description: What feature do you want added to Re-Console?
    validations:
      required: true
  - type: textarea
    id: problem-relation
    attributes:
      label: Is your feature request related to a problem?
      description: Please provide a clear and concise description of what the problem is. (If applicable)
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: What should be done about this?
      description: Describe the solution you'd like
    validations:
      required: true
  - type: textarea
    id: extras
    attributes:
      label: Additional Context
      description: Put any extra info you feel is nessecary here.
  - type: checkboxes
    id: terms
    attributes:
      label: Acknowledgement
      description: If you do not fill out this form correctly, your issue will be immediately closed.
      options:
        - label: I understand and have fully filled out the form.
          required: true
