name = "Re-Console Lite"
author = "omo50"
version = "1.0.0+mc1.21.4+fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7545b48c3f8c59f7f7f7f0b79bb5faa02da752ba9c1816a24cef74b5e2277233"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
